### ISSUE TITLE
Caster Mob/Hidden Thief behavior summary

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#922] opened 2021-09-24 21:23 UTC
When a thief is hidden, if casters or archers move to 1 hex away,  the mobs get somewhat confused.  They see me and are threatened by me, thus move away from me.  When moving away from me, they cannot see me anymore, so at that point they move directly to the hex im standing in.  Each round, they move back to their original hex, and then back to my hex, in an infinite loop, until I either unhide or kill them.  There is a special circumstance.  IF a caster mob is stuck in this loop, and i then kill a DIFFERENT MOB while the caster mob is standing on my hex, it will then warm a spell and try to kill me.  Apparently killing a different mob in the caster mob's presence makes him decide to kill me right away instead of continuing to retreat on sight.   [Report by Xero]

**Comment by jkachhad** [comment] 2021-09-26 03:00
> IF a caster mob is stuck in this loop, and i then kill a DIFFERENT MOB while the caster mob is standing on my hex, it will then warm a spell and try to kill me. Apparently killing a different mob in the caster mob's presence makes him decide to kill me right away instead of continuing to retreat on sight. [Report by Xero]

This is intended behavior. Casters will move back to a safe location if other AI are present to safely cast while the other AI will tank your attacks.  If there are no other AI, the caster will choose to simply cast as it knows moving to a safe location means you will not be visible.

**Closed by jkachhad** 2021-09-26 03:00 UTC
