### ISSUE TITLE
thief door

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#948] opened 2021-10-07 05:45 UTC
can still walk in lars thief door Uk where you used to have to go to get poison spell [Reported by bulsie]

**Comment by yarrim** [comment] 2021-11-12 01:36
duplicate of #949

**Comment by Tawnos-LOK** [comment] 2022-01-26 21:16
Closing, as it is a duplicate of #949

**Closed by Tawnos-LOK** 2022-01-26 21:16 UTC
