### ISSUE TITLE
Vulcan Room - Character Bug

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1199] opened 2022-01-17 22:12 UTC
Related to Issue 1190, this is a weird one and complex.  After fearing Vulcan and Alia into fire and having them killed (which no longer crashes the server), logging out on my Thaum and back in presents with a completely black map as is he is blinded when he isn't.  Attempting to move or even Exit from this state causes a character disconnect and possible crash condition.  I hypothesize that this bugged state might be due to an incomplete fix to the 1190 crash but cannot verify what is really happening on a debug level [Reported by Vernak]

**Comment by Tawnos-LOK** [comment] 2022-01-26 00:45
Cannot reproduce issue any longer.  Closing.

**Closed by Tawnos-LOK** 2022-01-26 00:45 UTC
