### ISSUE TITLE
tried to climb up to oak town and died

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#964] opened 2021-10-11 15:21 UTC
i clicked the rope to climb up and I insta died.

oct 11th 2021 [Report by Midgit]

**Comment by yarrim** [comment] 2021-10-11 21:00
That rope has 0 slip chance according to WorldForge.

Also, duplicate of https://github.com/jkachhad/Stormhalter/issues/860

**Closed as completed** 2021-10-24 01:48 UTC
